// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practice_1_ASP.Data;

#nullable disable

namespace Practice_1_ASP.Migrations
{
    [DbContext(typeof(FilmDbContext))]
    [Migration("20250223115234_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FilmModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FilmModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            Description = "A thief who enters the dreams of others.",
                            DurationMinutes = 148,
                            Genre = "Sci-Fi",
                            Name = "Inception",
                            Photo = "https://m.media-amazon.com/images/I/51oD6hAZQYL._AC_SY679_.jpg",
                            Year = 2010
                        },
                        new
                        {
                            Id = 2,
                            Country = "USA",
                            Description = "Batman faces the Joker in Gotham.",
                            DurationMinutes = 152,
                            Genre = "Action",
                            Name = "The Dark Knight",
                            Photo = "https://m.media-amazon.com/images/I/71p8G+Lpt0L._AC_SY679_.jpg",
                            Year = 2008
                        },
                        new
                        {
                            Id = 3,
                            Country = "USA",
                            Description = "A tragic love story aboard the Titanic.",
                            DurationMinutes = 195,
                            Genre = "Drama",
                            Name = "Titanic",
                            Photo = "https://m.media-amazon.com/images/I/71w-PqrXoXL._AC_SY679_.jpg",
                            Year = 1997
                        },
                        new
                        {
                            Id = 4,
                            Country = "USA",
                            Description = "A hacker discovers the nature of reality.",
                            DurationMinutes = 136,
                            Genre = "Sci-Fi",
                            Name = "The Matrix",
                            Photo = "https://m.media-amazon.com/images/I/51EG732BV3L.jpg",
                            Year = 1999
                        },
                        new
                        {
                            Id = 5,
                            Country = "USA",
                            Description = "Intertwined stories of crime and redemption.",
                            DurationMinutes = 154,
                            Genre = "Crime",
                            Name = "Pulp Fiction",
                            Photo = "https://m.media-amazon.com/images/I/71c05lTE03L._AC_SY679_.jpg",
                            Year = 1994
                        },
                        new
                        {
                            Id = 6,
                            Country = "USA",
                            Description = "A man imprisoned for a crime he didn't commit.",
                            DurationMinutes = 142,
                            Genre = "Drama",
                            Name = "The Shawshank Redemption",
                            Photo = "https://m.media-amazon.com/images/I/51zUbui+gbL.jpg",
                            Year = 1994
                        },
                        new
                        {
                            Id = 7,
                            Country = "USA",
                            Description = "A man with a low IQ influences history.",
                            DurationMinutes = 142,
                            Genre = "Drama",
                            Name = "Forrest Gump",
                            Photo = "https://m.media-amazon.com/images/I/71VXTI-XOQL._AC_SY679_.jpg",
                            Year = 1994
                        },
                        new
                        {
                            Id = 8,
                            Country = "USA",
                            Description = "A space mission to save humanity.",
                            DurationMinutes = 169,
                            Genre = "Sci-Fi",
                            Name = "Interstellar",
                            Photo = "https://m.media-amazon.com/images/I/91kFYg4fX3L._AC_SY679_.jpg",
                            Year = 2014
                        },
                        new
                        {
                            Id = 9,
                            Country = "USA",
                            Description = "An insomniac and a soap salesman start an underground fight club.",
                            DurationMinutes = 139,
                            Genre = "Drama",
                            Name = "Fight Club",
                            Photo = "https://m.media-amazon.com/images/I/81sA2zAxL9L._AC_SY679_.jpg",
                            Year = 1999
                        },
                        new
                        {
                            Id = 10,
                            Country = "USA",
                            Description = "A betrayed general seeks revenge in Rome.",
                            DurationMinutes = 155,
                            Genre = "Action",
                            Name = "Gladiator",
                            Photo = "https://m.media-amazon.com/images/I/51y-0gpiHCL.jpg",
                            Year = 2000
                        },
                        new
                        {
                            Id = 11,
                            Country = "USA",
                            Description = "A mafia family's rise and struggle.",
                            DurationMinutes = 175,
                            Genre = "Crime",
                            Name = "The Godfather",
                            Photo = "https://m.media-amazon.com/images/I/51sl+4W5vIL.jpg",
                            Year = 1972
                        },
                        new
                        {
                            Id = 12,
                            Country = "New Zealand",
                            Description = "A hobbit sets out to destroy a powerful ring.",
                            DurationMinutes = 178,
                            Genre = "Fantasy",
                            Name = "The Lord of the Rings: The Fellowship of the Ring",
                            Photo = "https://m.media-amazon.com/images/I/51Qvs9i5a%2BL.jpg",
                            Year = 2001
                        },
                        new
                        {
                            Id = 13,
                            Country = "New Zealand",
                            Description = "The battle for Middle-earth intensifies.",
                            DurationMinutes = 179,
                            Genre = "Fantasy",
                            Name = "The Lord of the Rings: The Two Towers",
                            Photo = "https://m.media-amazon.com/images/I/51GndkbMJDL._AC_.jpg",
                            Year = 2002
                        },
                        new
                        {
                            Id = 14,
                            Country = "New Zealand",
                            Description = "The final battle for Middle-earth.",
                            DurationMinutes = 201,
                            Genre = "Fantasy",
                            Name = "The Lord of the Rings: The Return of the King",
                            Photo = "https://m.media-amazon.com/images/I/91kTZZKpxeL._AC_SY679_.jpg",
                            Year = 2003
                        },
                        new
                        {
                            Id = 15,
                            Country = "USA",
                            Description = "A marine on an alien planet must choose sides.",
                            DurationMinutes = 162,
                            Genre = "Sci-Fi",
                            Name = "Avatar",
                            Photo = "https://m.media-amazon.com/images/I/41p+5VEzbIL._AC_.jpg",
                            Year = 2009
                        },
                        new
                        {
                            Id = 16,
                            Country = "USA",
                            Description = "Earth's mightiest heroes team up to stop Loki.",
                            DurationMinutes = 143,
                            Genre = "Action",
                            Name = "The Avengers",
                            Photo = "https://m.media-amazon.com/images/I/71rXSVqETkL._AC_SY679_.jpg",
                            Year = 2012
                        },
                        new
                        {
                            Id = 17,
                            Country = "USA",
                            Description = "A failed comedian descends into madness.",
                            DurationMinutes = 122,
                            Genre = "Drama",
                            Name = "Joker",
                            Photo = "https://m.media-amazon.com/images/I/71zWYYM4aFL._AC_SY679_.jpg",
                            Year = 2019
                        },
                        new
                        {
                            Id = 18,
                            Country = "USA",
                            Description = "Peter Parker deals with multiverse consequences.",
                            DurationMinutes = 148,
                            Genre = "Action",
                            Name = "Spider-Man: No Way Home",
                            Photo = "https://m.media-amazon.com/images/I/71nz3cIcFOL._AC_SY679_.jpg",
                            Year = 2021
                        },
                        new
                        {
                            Id = 19,
                            Country = "USA",
                            Description = "A noble family fights for control of a desert planet.",
                            DurationMinutes = 155,
                            Genre = "Sci-Fi",
                            Name = "Dune",
                            Photo = "https://m.media-amazon.com/images/I/81dGM9EEGHL._AC_SY679_.jpg",
                            Year = 2021
                        },
                        new
                        {
                            Id = 20,
                            Country = "USA",
                            Description = "The story of the man who built the atomic bomb.",
                            DurationMinutes = 180,
                            Genre = "Biography",
                            Name = "Oppenheimer",
                            Photo = "https://m.media-amazon.com/images/I/71TqLRP8R3L._AC_SY679_.jpg",
                            Year = 2023
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
